// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    title, description, category, venue, address, city, country,
    image_url, start_date, end_date, status, is_featured, organizer_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, title, description, category, venue, address, city, country, image_url,
          start_date, end_date, status, is_featured, organizer_id, moderator_id,
          moderation_comment, moderated_at, created_at, updated_at, deleted_at
`

type CreateEventParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Category    pgtype.Text        `json:"category"`
	Venue       string             `json:"venue"`
	Address     pgtype.Text        `json:"address"`
	City        pgtype.Text        `json:"city"`
	Country     pgtype.Text        `json:"country"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	EndDate     pgtype.Timestamptz `json:"end_date"`
	Status      string             `json:"status"`
	IsFeatured  bool               `json:"is_featured"`
	OrganizerID pgtype.UUID        `json:"organizer_id"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Venue,
		arg.Address,
		arg.City,
		arg.Country,
		arg.ImageUrl,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.IsFeatured,
		arg.OrganizerID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Venue,
		&i.Address,
		&i.City,
		&i.Country,
		&i.ImageUrl,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.IsFeatured,
		&i.OrganizerID,
		&i.ModeratorID,
		&i.ModerationComment,
		&i.ModeratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, title, description, category, venue, address, city, country, image_url,
       start_date, end_date, status, is_featured, organizer_id, moderator_id,
       moderation_comment, moderated_at, created_at, updated_at, deleted_at
FROM events
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Venue,
		&i.Address,
		&i.City,
		&i.Country,
		&i.ImageUrl,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.IsFeatured,
		&i.OrganizerID,
		&i.ModeratorID,
		&i.ModerationComment,
		&i.ModeratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, description, category, venue, address, city, country, image_url,
       start_date, end_date, status, is_featured, organizer_id, moderator_id,
       moderation_comment, moderated_at, created_at, updated_at, deleted_at
FROM events
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Venue,
			&i.Address,
			&i.City,
			&i.Country,
			&i.ImageUrl,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.IsFeatured,
			&i.OrganizerID,
			&i.ModeratorID,
			&i.ModerationComment,
			&i.ModeratedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventStatus = `-- name: UpdateEventStatus :one
UPDATE events
SET
    status             = $2,
    moderator_id       = $3,
    moderation_comment = $4,
    moderated_at       = $5,
    updated_at         = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, description, category, venue, address, city, country, image_url,
          start_date, end_date, status, is_featured, organizer_id, moderator_id,
          moderation_comment, moderated_at, created_at, updated_at, deleted_at
`

type UpdateEventStatusParams struct {
	ID                pgtype.UUID        `json:"id"`
	Status            string             `json:"status"`
	ModeratorID       pgtype.UUID        `json:"moderator_id"`
	ModerationComment pgtype.Text        `json:"moderation_comment"`
	ModeratedAt       pgtype.Timestamptz `json:"moderated_at"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventStatus,
		arg.ID,
		arg.Status,
		arg.ModeratorID,
		arg.ModerationComment,
		arg.ModeratedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Venue,
		&i.Address,
		&i.City,
		&i.Country,
		&i.ImageUrl,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.IsFeatured,
		&i.OrganizerID,
		&i.ModeratorID,
		&i.ModerationComment,
		&i.ModeratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
