// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       string             `json:"color"`
	Icon        pgtype.Text        `json:"icon"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Category          pgtype.Text        `json:"category"`
	Venue             string             `json:"venue"`
	Address           pgtype.Text        `json:"address"`
	City              pgtype.Text        `json:"city"`
	Country           pgtype.Text        `json:"country"`
	ImageUrl          pgtype.Text        `json:"image_url"`
	StartDate         pgtype.Timestamptz `json:"start_date"`
	EndDate           pgtype.Timestamptz `json:"end_date"`
	Status            string             `json:"status"`
	IsFeatured        bool               `json:"is_featured"`
	OrganizerID       pgtype.UUID        `json:"organizer_id"`
	ModeratorID       pgtype.UUID        `json:"moderator_id"`
	ModerationComment pgtype.Text        `json:"moderation_comment"`
	ModeratedAt       pgtype.Timestamptz `json:"moderated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type OrganizerBalance struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizerID      pgtype.UUID        `json:"organizer_id"`
	TotalEarnings    pgtype.Numeric     `json:"total_earnings"`
	AvailableBalance pgtype.Numeric     `json:"available_balance"`
	PendingBalance   pgtype.Numeric     `json:"pending_balance"`
	WithdrawnAmount  pgtype.Numeric     `json:"withdrawn_amount"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PlatformSetting struct {
	ID                      pgtype.UUID        `json:"id"`
	PlatformFeePercentage   pgtype.Numeric     `json:"platform_fee_percentage"`
	WithdrawalFeePercentage pgtype.Numeric     `json:"withdrawal_fee_percentage"`
	MinWithdrawalAmount     pgtype.Numeric     `json:"min_withdrawal_amount"`
	Currency                string             `json:"currency"`
	UpdatedBy               pgtype.UUID        `json:"updated_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Ticket struct {
	ID            pgtype.UUID        `json:"id"`
	TicketNumber  string             `json:"ticket_number"`
	EventID       pgtype.UUID        `json:"event_id"`
	TicketTypeID  pgtype.UUID        `json:"ticket_type_id"`
	AttendeeID    pgtype.UUID        `json:"attendee_id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	Status        string             `json:"status"`
	Price         pgtype.Numeric     `json:"price"`
	QrCodeUrl     pgtype.Text        `json:"qr_code_url"`
	PdfUrl        pgtype.Text        `json:"pdf_url"`
	CheckedInAt   pgtype.Timestamptz `json:"checked_in_at"`
	CheckedInBy   pgtype.UUID        `json:"checked_in_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type TicketType struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	Quantity    int32              `json:"quantity"`
	Sold        int32              `json:"sold"`
	MaxPerOrder int32              `json:"max_per_order"`
	SaleStart   pgtype.Timestamptz `json:"sale_start"`
	SaleEnd     pgtype.Timestamptz `json:"sale_end"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	EventID          pgtype.UUID        `json:"event_id"`
	Type             string             `json:"type"`
	Status           string             `json:"status"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	PlatformFee      pgtype.Numeric     `json:"platform_fee"`
	NetAmount        pgtype.Numeric     `json:"net_amount"`
	PaymentGateway   pgtype.Text        `json:"payment_gateway"`
	PaymentReference pgtype.Text        `json:"payment_reference"`
	PaymentMetadata  []byte             `json:"payment_metadata"`
	Description      pgtype.Text        `json:"description"`
	FailureReason    pgtype.Text        `json:"failure_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	Password            string             `json:"password"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Phone               pgtype.Text        `json:"phone"`
	Role                string             `json:"role"`
	IsActive            bool               `json:"is_active"`
	IsVerified          bool               `json:"is_verified"`
	VerificationToken   pgtype.Text        `json:"verification_token"`
	VerificationExpiry  pgtype.Timestamptz `json:"verification_expiry"`
	PasswordResetToken  pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpiry pgtype.Timestamptz `json:"password_reset_expiry"`
	TwoFactorSecret     pgtype.Text        `json:"two_factor_secret"`
	TwoFactorEnabled    bool               `json:"two_factor_enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type WithdrawalRequest struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizerID    pgtype.UUID        `json:"organizer_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	WithdrawalFee  pgtype.Numeric     `json:"withdrawal_fee"`
	NetAmount      pgtype.Numeric     `json:"net_amount"`
	Status         string             `json:"status"`
	BankName       string             `json:"bank_name"`
	AccountNumber  string             `json:"account_number"`
	AccountName    string             `json:"account_name"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	ReviewComment  pgtype.Text        `json:"review_comment"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	TransactionRef pgtype.Text        `json:"transaction_ref"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
