// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    ticket_number, event_id, ticket_type_id, attendee_id, transaction_id,
    status, price, qr_code_url, pdf_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, ticket_number, event_id, ticket_type_id, attendee_id, transaction_id,
          status, price, qr_code_url, pdf_url, checked_in_at, checked_in_by,
          created_at, updated_at, deleted_at
`

type CreateTicketParams struct {
	TicketNumber  string         `json:"ticket_number"`
	EventID       pgtype.UUID    `json:"event_id"`
	TicketTypeID  pgtype.UUID    `json:"ticket_type_id"`
	AttendeeID    pgtype.UUID    `json:"attendee_id"`
	TransactionID pgtype.UUID    `json:"transaction_id"`
	Status        string         `json:"status"`
	Price         pgtype.Numeric `json:"price"`
	QrCodeUrl     pgtype.Text    `json:"qr_code_url"`
	PdfUrl        pgtype.Text    `json:"pdf_url"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.TicketNumber,
		arg.EventID,
		arg.TicketTypeID,
		arg.AttendeeID,
		arg.TransactionID,
		arg.Status,
		arg.Price,
		arg.QrCodeUrl,
		arg.PdfUrl,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeID,
		&i.TransactionID,
		&i.Status,
		&i.Price,
		&i.QrCodeUrl,
		&i.PdfUrl,
		&i.CheckedInAt,
		&i.CheckedInBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, ticket_number, event_id, ticket_type_id, attendee_id, transaction_id,
       status, price, qr_code_url, pdf_url, checked_in_at, checked_in_by,
       created_at, updated_at, deleted_at
FROM tickets
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.EventID,
		&i.TicketTypeID,
		&i.AttendeeID,
		&i.TransactionID,
		&i.Status,
		&i.Price,
		&i.QrCodeUrl,
		&i.PdfUrl,
		&i.CheckedInAt,
		&i.CheckedInBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketsByEvent = `-- name: GetTicketsByEvent :many
SELECT id, ticket_number, event_id, ticket_type_id, attendee_id, transaction_id,
       status, price, qr_code_url, pdf_url, checked_in_at, checked_in_by,
       created_at, updated_at, deleted_at
FROM tickets
WHERE event_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetTicketsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, getTicketsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TicketNumber,
			&i.EventID,
			&i.TicketTypeID,
			&i.AttendeeID,
			&i.TransactionID,
			&i.Status,
			&i.Price,
			&i.QrCodeUrl,
			&i.PdfUrl,
			&i.CheckedInAt,
			&i.CheckedInBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
