// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, event_id, type, status, amount, currency, platform_fee, net_amount,
    payment_gateway, payment_reference, payment_metadata, description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, event_id, type, status, amount, currency, platform_fee, net_amount,
          payment_gateway, payment_reference, payment_metadata, description, failure_reason,
          created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	UserID           pgtype.UUID    `json:"user_id"`
	EventID          pgtype.UUID    `json:"event_id"`
	Type             string         `json:"type"`
	Status           string         `json:"status"`
	Amount           pgtype.Numeric `json:"amount"`
	Currency         string         `json:"currency"`
	PlatformFee      pgtype.Numeric `json:"platform_fee"`
	NetAmount        pgtype.Numeric `json:"net_amount"`
	PaymentGateway   pgtype.Text    `json:"payment_gateway"`
	PaymentReference pgtype.Text    `json:"payment_reference"`
	PaymentMetadata  []byte         `json:"payment_metadata"`
	Description      pgtype.Text    `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.EventID,
		arg.Type,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.PlatformFee,
		arg.NetAmount,
		arg.PaymentGateway,
		arg.PaymentReference,
		arg.PaymentMetadata,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PaymentGateway,
		&i.PaymentReference,
		&i.PaymentMetadata,
		&i.Description,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByReference = `-- name: GetTransactionByReference :one
SELECT id, user_id, event_id, type, status, amount, currency, platform_fee, net_amount,
       payment_gateway, payment_reference, payment_metadata, description, failure_reason,
       created_at, updated_at, deleted_at
FROM transactions
WHERE payment_reference = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTransactionByReference(ctx context.Context, paymentReference pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByReference, paymentReference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PaymentGateway,
		&i.PaymentReference,
		&i.PaymentMetadata,
		&i.Description,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET
    status         = $2,
    failure_reason = COALESCE($3, failure_reason),
    updated_at     = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, event_id, type, status, amount, currency, platform_fee, net_amount,
          payment_gateway, payment_reference, payment_metadata, description, failure_reason,
          created_at, updated_at, deleted_at
`

type UpdateTransactionStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.ID, arg.Status, arg.FailureReason)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PlatformFee,
		&i.NetAmount,
		&i.PaymentGateway,
		&i.PaymentReference,
		&i.PaymentMetadata,
		&i.Description,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
