// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password, first_name, last_name, phone, role,
    is_active, is_verified, two_factor_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, email, password, first_name, last_name, phone, role, is_active, is_verified,
          verification_token, verification_expiry, password_reset_token, password_reset_expiry,
          two_factor_secret, two_factor_enabled, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email            string      `json:"email"`
	Password         string      `json:"password"`
	FirstName        string      `json:"first_name"`
	LastName         string      `json:"last_name"`
	Phone            pgtype.Text `json:"phone"`
	Role             string      `json:"role"`
	IsActive         bool        `json:"is_active"`
	IsVerified       bool        `json:"is_verified"`
	TwoFactorEnabled bool        `json:"two_factor_enabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Role,
		arg.IsActive,
		arg.IsVerified,
		arg.TwoFactorEnabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationExpiry,
		&i.PasswordResetToken,
		&i.PasswordResetExpiry,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, first_name, last_name, phone, role, is_active, is_verified,
       verification_token, verification_expiry, password_reset_token, password_reset_expiry,
       two_factor_secret, two_factor_enabled, created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationExpiry,
		&i.PasswordResetToken,
		&i.PasswordResetExpiry,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, first_name, last_name, phone, role, is_active, is_verified,
       verification_token, verification_expiry, password_reset_token, password_reset_expiry,
       two_factor_secret, two_factor_enabled, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationExpiry,
		&i.PasswordResetToken,
		&i.PasswordResetExpiry,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name           = COALESCE($2, first_name),
    last_name            = COALESCE($3, last_name),
    phone                = COALESCE($4, phone),
    is_active            = COALESCE($5, is_active),
    is_verified          = COALESCE($6, is_verified),
    verification_token   = COALESCE($7, verification_token),
    verification_expiry  = COALESCE($8, verification_expiry),
    password_reset_token = COALESCE($9, password_reset_token),
    password_reset_expiry = COALESCE($10, password_reset_expiry),
    two_factor_secret    = COALESCE($11, two_factor_secret),
    two_factor_enabled   = COALESCE($12, two_factor_enabled),
    updated_at           = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password, first_name, last_name, phone, role, is_active, is_verified,
          verification_token, verification_expiry, password_reset_token, password_reset_expiry,
          two_factor_secret, two_factor_enabled, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID                  pgtype.UUID        `json:"id"`
	FirstName           pgtype.Text        `json:"first_name"`
	LastName            pgtype.Text        `json:"last_name"`
	Phone               pgtype.Text        `json:"phone"`
	IsActive            pgtype.Bool        `json:"is_active"`
	IsVerified          pgtype.Bool        `json:"is_verified"`
	VerificationToken   pgtype.Text        `json:"verification_token"`
	VerificationExpiry  pgtype.Timestamptz `json:"verification_expiry"`
	PasswordResetToken  pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpiry pgtype.Timestamptz `json:"password_reset_expiry"`
	TwoFactorSecret     pgtype.Text        `json:"two_factor_secret"`
	TwoFactorEnabled    pgtype.Bool        `json:"two_factor_enabled"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.IsActive,
		arg.IsVerified,
		arg.VerificationToken,
		arg.VerificationExpiry,
		arg.PasswordResetToken,
		arg.PasswordResetExpiry,
		arg.TwoFactorSecret,
		arg.TwoFactorEnabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationExpiry,
		&i.PasswordResetToken,
		&i.PasswordResetExpiry,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
